import { StyleSheet } from 'react-native';
import { 
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';

export const createSessionStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFF8EE',
    padding: wp(5),
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: hp(2),
    marginBottom: hp(3),
  },
  backButton: {
    padding: wp(2),
  },
  headerTitle: {
    fontSize: wp(5),
    fontFamily: 'Urbanist-Bold',
    color: '#000',
    marginLeft: wp(3),
  },
  sectionTitle: {
    fontSize: wp(4.5),
    fontFamily: 'Urbanist-SemiBold',
    color: '#000',
    marginBottom: hp(1.5),
  },
  inputContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: wp(3),
    paddingHorizontal: wp(4),
    paddingVertical: hp(1.8),
    marginBottom: hp(3),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  input: {
    fontFamily: 'Urbanist-Regular',
    fontSize: wp(4),
    color: '#7D7D7D',
  },
  dropdownContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: wp(3),
    marginBottom: hp(3),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  dropdown: {
    paddingHorizontal: wp(4),
    paddingVertical: hp(1.8),
    borderRadius: wp(3),
  },
  dropdownText: {
    fontFamily: 'Urbanist-Regular',
    fontSize: wp(4),
    color: '#7D7D7D',
  },
  dropdownIcon: {
    width: wp(5),
    height: wp(5),
    resizeMode: 'contain',
  },
  notesInput: {
    backgroundColor: '#FFFFFF',
    borderRadius: wp(3),
    paddingHorizontal: wp(4),
    paddingVertical: hp(1.8),
    marginBottom: hp(3),
    height: hp(15),
    textAlignVertical: 'top',
    fontFamily: 'Urbanist-Regular',
    fontSize: wp(4),
    color: '#7D7D7D',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: hp(2),
  },
  cancelButton: {
    backgroundColor: '#F2F2F2',
    borderRadius: wp(6),
    paddingVertical: hp(1.8),
    paddingHorizontal: wp(6),
    alignItems: 'center',
    justifyContent: 'center',
    width: wp(30),
  },
  cancelButtonText: {
    fontFamily: 'Urbanist-SemiBold',
    fontSize: wp(4),
    color: '#000',
  },
  submitButton: {
    backgroundColor: '#1E5631',
    borderRadius: wp(6),
    paddingVertical: hp(1.8),
    paddingHorizontal: wp(6),
    alignItems: 'center',
    justifyContent: 'center',
    width: wp(30),
  },
  submitButtonText: {
    fontFamily: 'Urbanist-SemiBold',
    fontSize: wp(4),
    color: '#FFFFFF',
  },
});