// import { Dimensions } from 'react-native';
import { StyleSheet } from 'react-native';
const styles = (wp: any, hp: any) =>
  StyleSheet.create({
    mainContainer: {
      flex: 1,
      position: 'relative',
    },
    menuItem: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: hp(1),
    },
    menuText: {
      marginLeft: wp(2),
      fontSize: wp(3.8),
      color: '#000',
    },

    bgimg: {
      flex: 1,
      resizeMode: 'cover',
    },
    mainScrollView: {
      flex: 1,
    },
    innercontainer: {
      borderRadius: 15,
      paddingTop: hp(2),
      paddingBottom: hp(10),
      marginTop: hp(2),
    },
    container: {
      flex: 0,
      padding: 14,
      marginTop: hp(1),
    },
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: hp(2),
    },
    logo: {
      width: wp(40),
      height: hp(6),
      resizeMode: 'contain',
    },
    headerText: {
      fontSize: 22,
      marginTop: hp(-0.5),
      color: '#000',
      marginLeft: hp(0),
      fontFamily: 'Poopins-Bold',
      fontWeight: '700',
    },
    headerIcons: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    bellIcon: {
      width: wp(6),
      height: wp(6),
      marginRight: wp(3),
    },
    userIcon: {
      width: wp(8),
      height: wp(8),
      borderRadius: wp(4),
    },
    featureRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      flexWrap: 'wrap',
      marginBottom: hp(3),
      marginTop: hp(1.5),
      marginHorizontal: hp(2.4),
    },
    featureBtn: {
      width: wp(19),
      height: wp(21),
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: hp(2),
    },
    featureIcon: {
      width: wp(15),
      height: wp(15),
      marginBottom: hp(1),
      resizeMode: 'cover',
    },
    // featureText: {
    //   fontSize: wp(2.8),
    //   textAlign: 'center',
    //   fontFamily: 'Poppins-SemiBold',
    // },
    servicesContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: hp(3),
      marginTop: hp(1.5),
      paddingHorizontal: wp(2),
      gap: wp(2),
    },
    serviceCard: {
      width: wp(22),
      height: wp(28),
      borderRadius: wp(3),
      overflow: 'hidden',
      borderWidth: 1,
      borderColor: '#264734',
      position: 'relative',
    },
    serviceCardIcon: {
      width: wp(22),
      height: wp(28),
      borderRadius: wp(0),
      alignItems: 'center',
      justifyContent: 'center',
      padding: wp(2),
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    serviceImage: {
      width: '100%',
      height: '100%',
      resizeMode: 'cover',
      borderRadius: wp(3),
    },
    serviceIcon: {
      width: wp(12),
      height: wp(12),
      resizeMode: 'cover',
      marginBottom: hp(0.5),
      tintColor: '#264734',
    },
    serviceOverlay: {
      position: 'absolute',
      bottom: 0,
      left: 0,
      right: 0,
      paddingVertical: hp(1),
      paddingHorizontal: wp(1.5),
      alignItems: 'center',
      borderBottomLeftRadius: wp(3),
      borderBottomRightRadius: wp(3),
    },
    serviceText: {
      fontSize: wp(2.8),
      color: '#fff',
      fontFamily: 'Poppins-SemiBold',
      textAlign: 'center',
      lineHeight: wp(3.5),
    },
    serviceTextIcon: {
      fontSize: wp(2.8),
      color: '#264734',
      fontFamily: 'Poppins-SemiBold',
      textAlign: 'center',
      lineHeight: wp(3.5),
    },
    sectionHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: hp(1),
      marginTop: hp(-1.5),
    },
    /* ---------------- Calendar & Earnings Grid ---------------- */
    gridRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
      rowGap: hp(2), // use rowGap/columnGap instead of gap
    },
    gridItem: {
      width: '48%',
      backgroundColor: '#fff',
      borderRadius: wp(4),
      padding: wp(4),
      // Shadow (iOS) + elevation (Android)
      // shadowColor: '#000',
      // shadowOpacity: 0.08,
      // shadowOffset: { width: 0, height: 4 },
      // shadowRadius: 12,
      // elevation: 3,
    },

    // headers
    calendarHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: hp(1.2),
    },
    sectionTitle: {
      fontSize: wp(4.2),
      fontWeight: '600',
      color: '#0b0b0b',
    },

    sectionHeaderWeek: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: hp(1.5),
    },
    rowStart: {
      flexDirection: 'row',
      alignItems: 'center',
      columnGap: wp(2.5),
    },
    // sessionIcon: {
    //   width: wp(5.5),
    //   height: wp(5.5),
    // },
    sectionTitleWeek: {
      fontSize: wp(3.8),
      color: '#1f3b2e',
      fontWeight: '500',
    },

    // calendar card
    calendarCard: {
      borderRadius: wp(0),
      padding: wp(2),
    },
    calendarTitle: {
      fontSize: 10,
      color: '#68866f',
      marginBottom: hp(0),
    },

    // earning card
    earningCard: {
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: hp(4),
      borderRadius: wp(4),
      backgroundColor: '#ffffff',
    },
    walletIcon: {
      width: wp(10),
      height: wp(10),
      marginBottom: hp(1),
    },
    earningText: {
      fontSize: wp(6),
      fontWeight: '700',
      color: '#1f3b2e',
      marginBottom: hp(1.6),
    },
    withdrawBtn: {
      paddingVertical: hp(1.5),
      width: wp(35),
      backgroundColor: '#2f5a3f',
      borderRadius: wp(10),
    },
    withdrawText: {
      color: '#fff',
      fontSize: 13,
      fontWeight: '600',
      textAlign:'center'
    },
    sectionHeaderweek: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: hp(1),
      marginTop: hp(-1.5),
      marginLeft: hp(12),
    },
    sessionIcon: {
      width: wp(6),
      height: wp(6),
      alignSelf: 'center',
    },
    providerIcon: {
      width: wp(12),
      height: wp(12),
      alignSelf: 'center',
    },
    // sectionTitle: {
    //   fontSize: 15,
    //   fontWeight: '700',
    //   fontFamily: 'Poppins-Bold',
    // },
    sectionTitleweek: {
      fontSize: 13,
      fontWeight: '700',
      fontFamily: 'Poppins-Bold',
      color: '#264734',
    },
    arrow: {
      fontSize: wp(10),
      color: '#000',
    },
    sessionCard: {
      width: wp(35),
      backgroundColor: '#fff',
      borderRadius: wp(4),
      padding: wp(3),
      marginRight: wp(3),
      marginBottom: hp(2),
    },
    sessionImg: {
      width: '89%',
      height: hp(12),
      borderRadius: wp(5),
      marginBottom: hp(2),
      resizeMode: 'cover',
      alignSelf: 'center',
    },
    sessionContent: {
      flex: 1,
      justifyContent: 'space-between',
      gap: hp(0.5),
    },
    sessionTitle: {
      fontSize: 14,
      marginBottom: hp(0),
      marginTop: hp(-1),
      fontFamily: 'Poppins-Bold',
      color: '#000',
      textAlign: 'center',
    },
    sessionText: {
      fontSize: 14,
      color: '#6B7280',
      marginBottom: hp(0),
      fontFamily: 'Poppins-Regular',
      lineHeight: wp(4.5),
      textAlign: 'center',
    },
    sessiontime: {
      fontSize: 13,
      color: '#000',
      textAlign: 'center',
      fontFamily: 'Poppins-Medium',
      fontWeight: '600',
    },
    detailsBtn: {
      backgroundColor: '#264734',
      paddingVertical: hp(1),
      borderRadius: wp(6),
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 3,
      elevation: 2,
    },
    detailsText: {
      color: '#fff',
      fontSize: 14,
      fontFamily: 'Poppins-SemiBold',
    },
    eventCard: {
      width: wp(55),
      backgroundColor: '#fff',
      borderRadius: wp(3),
      padding: wp(3),
      marginBottom: hp(2),
    },
    /* ---------------- Clients Section ---------------- */
    clientCard: {
      width: wp(54),
      backgroundColor: '#fff',
      borderRadius: wp(3),
      padding: wp(3),
      marginRight: wp(4), // 👈 adds space between cards
    },
    newreqCard: {
      width: wp(58),
      backgroundColor: '#fff',
      borderRadius: wp(3),
      padding: wp(3),
      marginRight: wp(4), // 👈 adds space between cards
    },
    clientTop: {
      alignItems: 'center',
      marginBottom: hp(1),
      flexDirection: 'row',
    },
    clientImg: {
      width: wp(14),
      height: wp(14),
      borderRadius: wp(9),
      alignSelf: 'center',
      marginBottom: hp(0),
      marginTop: hp(0.5),
    },
    clientName: {
      fontSize: 14,
      fontFamily: 'Poppins-Bold',
      marginLeft: wp(2),
      marginBottom: hp(),
      color: '#000',
    },
    clientTime: {
      fontSize: 10,
      fontFamily: 'Poppins-Bold',
      color: '#264734',
      marginBottom: hp(1),
      marginLeft: wp(2),
    },
    clientText: {
      fontSize: 11,
      fontFamily: 'Poppins-Regular',
      color: '#264734',
      marginBottom: hp(1),
      marginLeft: wp(2),
      marginRight: wp(15),
    },
    clientBtn: {
      backgroundColor: '#264734',
      paddingVertical: hp(0.6),
      width: wp(22),
      height: hp(2.8),
      borderRadius: wp(5),
    },
    clientBtn2: {
      backgroundColor: '#264734',
      paddingVertical: hp(0.56),
      width: wp(24),
      height: hp(2.8),
      borderRadius: wp(6),
    },
    clientBtnText: {
      color: '#fff',
      fontSize: 9,
      fontFamily: 'Poppins-Medium',
      textAlign: 'center',
    },
    clientBtnOutline: {
      borderWidth: 1,
      borderColor: '#264734',
      paddingVertical: hp(0.6),
      width: wp(22),
      height: hp(2.8),
      borderRadius: wp(5),
    },
    clientBtnOutline2: {
      borderWidth: 1,
      borderColor: '#264734',
      paddingVertical: hp(0.6),
      width: wp(24),
      height: hp(2.8),
      borderRadius: wp(6),
    },
    clientBtnOutlineText: {
      color: '#264734',
      fontSize: 8,
      fontFamily: 'Poppins-Medium',
      textAlign: 'center',
    },

    /* ---------------- Support Requests ---------------- */
    supportCard: {
      flexDirection: 'row',
      backgroundColor: '#fff',
      borderRadius: wp(3),
      padding: wp(3),
      marginBottom: hp(2),
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 2,
    },
    supportImg: {
      width: wp(14),
      height: wp(14),
      borderRadius: wp(7),
      marginRight: wp(3),
    },
    supportContent: {
      flex: 1,
    },
    supportName: {
      fontSize: wp(3.8),
      fontFamily: 'Poppins-SemiBold',
      color: '#000',
      marginBottom: hp(0.5),
    },
    supportText: {
      fontSize: wp(3.2),
      color: '#6B7280',
      fontFamily: 'Poppins-Regular',
      marginBottom: hp(1),
    },
    acceptBtn: {
      backgroundColor: '#264734',
      paddingVertical: hp(0.8),
      paddingHorizontal: wp(3),
      borderRadius: wp(5),
    },
    declineBtn: {
      borderWidth: 1,
      borderColor: '#E63946',
      paddingVertical: hp(0.8),
      paddingHorizontal: wp(3),
      borderRadius: wp(5),
    },
    btnText: {
      color: '#fff',
      fontSize: wp(3.2),
      fontFamily: 'Poppins-Medium',
    },
    btnDeclineText: {
      color: '#E63946',
      fontSize: wp(3.2),
      fontFamily: 'Poppins-Medium',
    },

    /* ---------------- Calendar & Earnings ---------------- */
    calendarcontainer: {
      flex: 1,
    },
    calendar: {
      flex: 1,
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    //    calendarHeader: {
    //   flexDirection: 'row',
    //   justifyContent: 'space-between',
    //   alignItems: 'center',
    //   marginBottom: hp(1),
    // },
    //     calendarImg: {
    //       width: '100%',
    //       height: hp(18),
    //       resizeMode: 'contain',
    //       marginTop: hp(1),
    //     },

    //     earningText: {
    //       fontSize: wp(5),
    //       fontFamily: 'Poppins-Bold',
    //       color: '#000',
    //       marginVertical: hp(1),
    //       textAlign: 'center',
    //     },
    //     withdrawBtn: {
    //       backgroundColor: '#264734',
    //       paddingVertical: hp(1),
    //       borderRadius: wp(5),
    //       alignItems: 'center',
    //       marginTop: hp(1),
    //     },
    //     withdrawText: {
    //       color: '#fff',
    //       fontSize: wp(3.5),
    //       fontFamily: 'Poppins-SemiBold',
    //     },

    statText: {
      fontSize: wp(3.2),
      color: '#000',
    },
    scrollContent: {
      flexGrow: 1,
      justifyContent: 'center',
      alignItems: 'center',
      paddingTop: hp(10),
    },
    backButton: {
      top: hp(3),
      width: wp(10),
      height: wp(10),
      justifyContent: 'center',
      alignItems: 'center',
    },
    title: {
      fontSize: wp(5),
      fontFamily: 'Poppins-Bold',
      marginTop: hp(-1),
      marginRight: hp(10),
      textAlign: 'center',
    },
    grid: {
      flexDirection: 'row',
      paddingHorizontal: wp(4),
      paddingVertical: hp(1),
      gap: wp(3),
    },
    featureBox: {
      width: wp(21),
      height: wp(26),
      borderRadius: wp(1.5),
      overflow: 'hidden',
      borderWidth: 0,
      borderColor: '#264734',
      position: 'relative',
      marginBottom: hp(-1),
    },
    featureOverlay: {
      position: 'absolute',
      bottom: 5,
      left: 0,
      right: 0,
      paddingVertical: hp(1),
      paddingHorizontal: wp(1),
      borderBottomRightRadius: wp(1),
      borderBottomLeftRadius: wp(1),
      alignItems: 'center',
      justifyContent: 'center',
    },
    featureImage: {
      width: '100%',
      height: '100%',
      borderRadius: wp(0),
      resizeMode: 'contain',
    },
    featureText: {
      fontSize: 8.5,
      textAlign: 'center',
      color: '#fff',
      fontFamily: 'Poppins-SemiBold',
      lineHeight: wp(3.2),
      fontWeight: '600',
    },
    // calendarTitle: {
    //   fontSize: 16,
    //   fontFamily: 'Poppins-Bold',
    //   color: '#000',
    //   marginBottom: hp(1),
    //   marginTop: hp(-1),
    //   fontWeight: '700',
    // },
    calendarContainer: {
      borderRadius: wp(4),
      padding: wp(2),
      width: wp(44),
      marginTop: hp(-3.5),
      marginLeft: hp(-2.5),
    },
    customCalendarHeader: {
      backgroundColor: '#264734',
      borderTopLeftRadius: 0,
      borderTopRightRadius: 0,
      paddingVertical: hp(0.5),
      paddingBottom: wp(1),
      paddingHorizontal: wp(2),
    },
    calendarHeaderYear: {
      color: '#BFC9C6',
      fontSize: 9,
      fontFamily: 'Montserrat-Medium',
    },
    calendarHeaderDate: {
      color: '#fff',
      fontSize: 9,
      fontFamily: 'Poppins-Bold',
      marginTop: hp(0.5),
    },
    calendarNav: {
      fontSize: 9,
      color: '#264734',
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: wp(0),
      backgroundColor: '#f5f5f5',
      paddingVertical: hp(0),
    },
    calendarGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
      marginTop: hp(1),

      paddingBottom: wp(-10),
    },
    calendarDay: {
      width: '13%',
      aspectRatio: 1,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: wp(2),
      marginBottom: hp(1),
      marginTop: hp(-1.4),
      padding: hp(0.6),
    },
    calendarDaySelected: {
      borderRadius: wp(10),
    },
    calendarDayText: {
      fontSize: 9,
      color: '#222',
      fontFamily: 'Montserrat-Medium',
    },
    calendarDayTextSelected: {
      color: '#000',
      fontFamily: 'Montserrat-Bold',
    },
    // Events Section Styles
    eventsSection: {
      marginTop: hp(3),
    },
    // sectionHeader: {
    //   flexDirection: 'row',
    //   justifyContent: 'space-between',
    //   alignItems: 'center',
    //   marginBottom: hp(2),
    // },
    // sectionTitle: {
    //   fontSize: wp(4.5),
    //   fontFamily: 'Poppins-SemiBold',
    //   color: '#264734',
    // },
    eventButtonsContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      gap: wp(3),
    },
    createSessionBtn: {
      flex: 1,
      backgroundColor: '#264734',
      paddingVertical: hp(1),
      borderRadius: wp(8),
      alignItems: 'center',
      justifyContent: 'center',
    },
    mySessionsBtn: {
      flex: 1,
      backgroundColor: '#264734',
      paddingVertical: hp(1),
      borderRadius: wp(8),
      alignItems: 'center',
      justifyContent: 'center',
    },
    sessionBtnText: {
      color: '#FFFFFF',
      fontFamily: 'Poppins-Medium',
      fontSize: wp(3.5),
    },

    // Provider Resources Section Styles
    resourcesSection: {
      marginTop: hp(6),
    },
    resourceCardsContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      gap: wp(3),
    },
    resourceCard: {
      flex: 1,
      backgroundColor: '#FFFFFF',
      borderRadius: wp(3),
      padding: wp(3),
    },
    resourceIconContainer: {
      marginBottom: hp(1),
    },
    resourceTitle: {
      fontSize: 11,
      fontFamily: 'Poppins-Bold',
      color: '#0F172A',
      fontWeight: '700',
      marginBottom: hp(0.5),
      textAlign: 'center',
    },

    resourceDesc: {
      fontSize: 11,
      fontFamily: 'Poppins-Regular',
      color: '#000000',
      marginBottom: hp(1.5),
      textAlign: 'auto',
    },
    resourceBtn: {
      backgroundColor: '#264734',
      paddingVertical: hp(1),
      width: wp(38),
      borderRadius: wp(6),
      alignItems: 'center',
      justifyContent: 'center',
    },
    resourceBtnText: {
      color: '#FFFFFF',
      fontFamily: 'Poppins-Medium',
      fontSize: 10,
      textAlign: 'center',
    },
  });

export default styles;
