
export type RootStackParamList = {
  splashScreen: undefined;
  OnboardingScreen: undefined;
  WelcomeScreen: undefined;
  LoginScreen: undefined;
  SignUpScreen: undefined;
  VerificationCode: undefined;
  SuccessScreen: undefined;
  VerifyCredentials: undefined;
  CredentailsSuccess: undefined;
  HomeScreen: undefined; // hosts BottomTabs
  CreateSessionScreen: undefined;
  SessionsScreen: undefined;
  SessionPaymentScreen: undefined;
  SendPaymentLink: undefined;
  TransactionHistory: undefined;
  RefundPaymentScreen: undefined;
  GrantAccess: undefined;
  NoteScreen: undefined;
  UploadScreen: undefined;
  ShareProgress: undefined;
  PastSessionScreen: undefined;
  SessionDetails: undefined;
  Breakout: undefined;
  BreakoutRooms: undefined;
  RescheduleSession: undefined;
  EditSession: undefined;
  SessionCancel: undefined;
  PaymentDetailsScreen: undefined;
  WithdrawalScreen: undefined;
  BankDetailsScreen : undefined;
  ChangePasswordScreen:undefined;
  NotificationsScreen: undefined;
  HelpScreen: undefined;
  SetRegularHoursScreen: undefined;
  SessionshomeScreen: undefined;
  ClientScreen: undefined;
  MyAppointment: undefined;
  AppointmentDetails: undefined;
  VerifyCredentialsPeer: undefined;
  HomeScreenPeer: undefined;
  RequestApprovalScreen: undefined;
  CreatePeerGroupScreen: undefined;
  ProgressScreen: undefined;
  ProfileScreen: undefined;
  SecurityPrivacyScreen: undefined;
  RescheduleScreen: undefined;
};